---
name: test
on:
  workflow_call:
    inputs:
      docker_is_changed:
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.20.3
          cache: true
      - run: go build -o /usr/local/bin/aqua ./cmd/aqua
      - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
      - run: aqua i -l
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run --timeout 120s
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: go test -v ./... -race -covermode=atomic

      - run: cp /usr/local/bin/aqua dist/aqua-docker
        if: inputs.docker_is_changed
      - run: docker build -t aquaproj-aqua-dev .
        if: inputs.docker_is_changed
